# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{exemplor-chaser}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Grimm", "Ryan Davis", "Eric Hodel", "Kevin Clark"]
  s.date = %q{2009-11-15}
  s.default_executable = %q{exemplor-chaser}
  s.description = %q{Lightweight mutation testing against exemplor}
  s.email = %q{andrew.j.grimm@gmail.com}
  s.executables = ["exemplor-chaser"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "bin/exemplor-chaser",
     "exemplor-chaser.gemspec",
     "lib/exemplor-chaser.rb"
  ]
  s.homepage = %q{http://andrewjgrimm.wordpress.com/2009/11/08/declare-war-on-everything-with-chaser/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Runner for chaser against exemplor}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<exemplor>, [">= 2000.2.0"])
    else
      s.add_dependency(%q<exemplor>, [">= 2000.2.0"])
    end
  else
    s.add_dependency(%q<exemplor>, [">= 2000.2.0"])
  end
end

